DROP DATABASE IF EXISTS ya9cs4aswdtysmf9;
CREATE DATABASE ya9cs4aswdtysmf9;
USE ya9cs4aswdtysmf9;

CREATE TABLE burgers(
id INT NOT NULL AUTO_INCREMENT,
burger_name VARCHAR(255) NOT NULL,
devoured BOOLEAN DEFAULT false,
PRIMARY KEY(id)
);
